### ISSUE TITLE
no applicable method for 'family' applied to an object of class "NULL"

### ISSUE THREAD

**Issue by minghong** [SONGDONGYUAN1994/scDesign3#10]
Hello,
When I run scdesign3, the following error occurs
```
Input Data Construction Start
Input Data Construction End
Start Marginal Fitting
Marginal Fitting End
Start Copula Fitting
Convert Residuals to Multivariate Gaussian
Error in UseMethod("family") : 
  no applicable method for 'family' applied to an object of class "NULL"
```
How can I solve it, thank you!

**Comment by SONGDONGYUAN1994** [comment]
Hi Minghong,
Without your reproducible code, it would be challenging to debug. Could you please show your code?

The first thing you may want to try is to use a subset of your original data; sometimes, the data can be too large for your RAM.

Best regards,
Dongyuan

**Comment by XiaPoppy** [comment]
Hi Dongyuan, 

I have the same question now when I am following the [tutorial for batch effect simulation](https://songdongyuan1994.github.io/scDesign3/docs/articles/scDesign3-batchEffect-vignette.html):

```R
simu_res <- scdesign3(sce = example_sce, 
                      assay_use = "counts", 
                      celltype = "cell_type", 
                      pseudotime = NULL, 
                      spatial = NULL, 
                      other_covariates = c("batch"), 
                      mu_formula = "cell_type + batch", 
                      sigma_formula = "1", 
                      family_use = "nb", 
                      n_cores = 1, 
                      usebam = FALSE, 
                      corr_formula = "1", 
                      copula = "gaussian", 
                      DT = TRUE, 
                      pseudo_obs = FALSE, 
                      return_model = FALSE)
```

And the error message is

> Input Data Construction Start
> Input Data Construction End
> Start Marginal Fitting
> Marginal Fitting End
> Start Copula Fitting
> Convert Residuals to Multivariate Gaussian
> Error in UseMethod("family") : 
>   no applicable method for 'family' applied to an object of class "NULL"

With macOS m1, and changed n_cores=1 in the function.

Best,
Danyang

**Comment by littlecabiria** [comment]
Hi Dongyuan,

I have similar problems. Some of my datasets can run, but some of them cannot run. Could you help me check it plz? 
Thank you so much!

```
real_sce <- readRDS("PDAC.rds")
sce_simu <- scdesign3(
    sce = real_sce,
    assay_use = "counts",
    celltype = "cell_type",
    pseudotime = NULL,
    spatial = c("row", "col"), # spatial location
    other_covariates = NULL, 
    mu_formula = "s(row, col, bs = 'gp', k= 100)",
    sigma_formula = "1",
    family_use = "nb", 
    n_cores = 1,
    usebam = TRUE,
    corr_formula = "1",
    copula = "gaussian", 
    DT = TRUE,
    pseudo_obs = FALSE,
    return_model = FALSE,
    nonzerovar = FALSE,
    parallelization = "mcmapply" 
  )
```

`scDesign3 Simulation Start
Input Data Construction Start
Input Data Construction End
Start Marginal Fitting
Marginal Fitting End
Start Copula Fitting
Convert Residuals to Multivariate Gaussian
Error in UseMethod("family") : 
  no applicable method for 'family' applied to an object of class "NULL"
In addition: There were 20 warnings (use warnings() to see them)`

[PDAC.rds.zip](https://github.com/SONGDONGYUAN1994/scDesign3/files/14000712/PDAC.rds.zip)

**Comment by SONGDONGYUAN1994** [comment]
@littlecabiria Hi Cabiria,
I checked your data and it seems like a bug with `usebam = TRUE`. Can you set `usebam = FALSE`? It works for me on my computer. It is probably because the spot numbers are relatively small (~400); thus, the fast version (bam) may not work well since it needs subsampling.

Best,
Dongyuan

**Comment by littlecabiria** [comment]
Hi Dongyuan,
Thank you so much! It works now!
