### ISSUE TITLE
possibility to know the cell type if I manually set the ncell parameter

### ISSUE THREAD

**Issue by XiaPoppy** [SONGDONGYUAN1994/scDesign3#16]
Dear Dongguan,

I am wondering, if I want to have more or less cells compared to the reference dataset, can I know the cell type for each cell? (and also the batch information needed)

Looking forward to your reply.

Best,
Danyang Xia

**Comment by SONGDONGYUAN1994** [comment]
Hi Danyang,
Yes, we do output the cell info. If you use the wrapper `scdeisgn3()`, the output should contain a value called `newCovaraites`. Instead, if you use step-by-step mode, you have to input newCovaraites manually. Let me know if you find it. 

Best,
Dongyuan

**Comment by XiaPoppy** [comment]
Hi Dongyuan,

Thanks for your reply and I found them.

Have a good day!

Best,
Danyang
