### ISSUE TITLE
Simulation from bulk RNA-seq

### ISSUE THREAD

**Issue by zji90** [SONGDONGYUAN1994/scDesign3#41]
Is it possible to use a bulk RNA-seq dataset as input to scDesign3?

**Comment by SONGDONGYUAN1994** [comment]
Hi Dr. Ji,
Yes, scDesign3 can simulate bulk RNA-seq data; although this is not included in our paper, my collaborators have used it in simulating bulk data. Conceptually, as long as the input is a count matrix, we can use it as the input. The challenge here is that the bulk sample size is smaller.

Best,
Dongyuan

**Comment by zji90** [comment]
This is great. Thanks!
