### ISSUE TITLE
Benchmarking SVG Methods: equal mean parameters

### ISSUE THREAD

**Issue by kinnaryshah** [SONGDONGYUAN1994/scDesign3#58]
Thank you for developing this package! I was looking through issue #43 and this [vignette](https://songdongyuan1994.github.io/scDesign3/docs/articles/scDesign3-DEanalysis-vignette.html#identification-of-spatially-variable-genes-svg-in-spatial-transcriptomic-data) for some help benchmarking SVG methods. Could you explain the reasoning for manually setting the mean parameters of non-SVG genes to be the same across all cells?

**Comment by SONGDONGYUAN1994** [comment]
Hi Kinnary,

In our simulation of spatial data, each spot is sampled independently based on its mean and variance. Even though we use the GP smoother in gene fitting, what we extract is the mean surface and variance parameter.

Therefore, under the non-SVG setting,  when we set the means of all spots the same, there are no spatial patterns of these genes; they are sampled completely i.i.d. This is definitely an extreme null case.

Best regards,
Dongyuan

**Comment by kinnaryshah** [comment]
Thank you!
