### ISSUE TITLE
Simulate scRNA-seq data with varying number of cells and/or sequencing depth on scDesign3

### ISSUE THREAD

**Issue by ShuyangNie** [SONGDONGYUAN1994/scDesign3#60]
Hi,

Thank you for bringing such a brilliant package! But I want to simulate data with varying number of cells and/or sequencing depth, which can be perfect performed on scDesign2 but was not mentioned on _Tutorial_. I wonder if this can be also performed on scDesign3 since I also need to simulate batch effect simultaneously. I will be more than grateful if you can give me any recommendations.

Best regards!
Shuyang

**Comment by SONGDONGYUAN1994** [comment]
Hi Shuyang,
Thank you for your interest in our package. Yes, scDesign3 can do varying cell numbers/sequencing depth.

For cell numbers, please check this tutorial: https://songdongyuan1994.github.io/scDesign3/docs/articles/scDesign3-cellType-vignette.html

For sequencing depth, please check this tutorial:
https://songdongyuan1994.github.io/scDesign3/docs/articles/scDesign3-librarySize-vignette.html

Please let me know if it works.

Best regards,
Dongyuan

**Comment by ShuyangNie** [comment]
Hi Dongyuan,

Thank you for your recommendation! I have tried to add adjustive factor on cell library size and number of cells and it works!

Best regards,
Shuyang
