### ISSUE TITLE
Error while simulating spot-resolution spatial data for cell-type deconvolution

### ISSUE THREAD

**Issue by sumeer1** [SONGDONGYUAN1994/scDesign3#9]
Hi,

I am trying to run the tutorial for simulating spot-resolution spatial data for cell-type deconvolution but I am getting error while running this block of code:

Error: Error in xtfrm.data.frame(x) : cannot xtfrm data frames
```
MOBSP_data <- construct_data(
  sce = MOBSP_sce,
  assay_use = "counts",
  celltype = NULL,
  pseudotime = NULL,
  spatial = c("spatial1", "spatial2"),
  other_covariates = NULL,
  corr_by = "1"
)
```

**Comment by qw130** [comment]
Hi Sumeer,

Thanks for your interest in our work and for pointing out this issue! I pushed the fixed code and now you should be able to run the tutorial for simulating spot-resolution spatial data for cell-type deconvolution with no issue.

Best,
Qingyang
